### ISSUE TITLE
Scala build error

### ISSUE THREAD

**Issue by matiasw** [mame/quine-relay#74]
Hi,
congratulations on your madness.
I am trying to build your Rube Goldberg Eternatron. I've got 83 K of Scala from your initial Ruby file, but then ran into trouble:

```
error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:45)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:66)
	at scala.reflect.internal.Mirrors$RootsBase.getClassByName(Mirrors.scala:102)
	at scala.reflect.internal.Mirrors$RootsBase.getRequiredClass(Mirrors.scala:105)
	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass$lzycompute(Definitions.scala:257)
	at scala.reflect.internal.Definitions$DefinitionsClass.ObjectClass(Definitions.scala:257)
	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1394)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1215)
	at scala.tools.nsc.Driver.doCompile(Driver.scala:31)
	at scala.tools.nsc.MainClass.doCompile(Main.scala:23)
	at scala.tools.nsc.Driver.process(Driver.scala:51)
	at scala.tools.nsc.Driver.main(Driver.scala:64)
	at scala.tools.nsc.Main.main(Main.scala)
```

I am using the build instructions provided "manually", because the Makefile complains that I do not have all the compilers (Scheme, in my case). That's true, but only because I lack the 3.5 GB of disk space to install all the missing ones (don't worry, I'll buy a new disk soon to rectify this!).
`ruby QR.rb > QR.scala`
completes fine.
`scalac QR.scala && scala QR > QR.scm`
yields the error above.

**Comment by mame** [comment]
I'm not sure but I guess your scala setup is broken.  I can find [some issues reported with the error message](https://www.google.co.jp/search?q=%22object+java.lang.Object+in+compiler+mirror+not+found%22).  Can you run a normal hello world program written in Scala?

Or, please compare your QR.scala with [this file](https://raw.githubusercontent.com/mame/quine-relay/spoiler/QR.scala).  If they are different, there is an issue in the previous stage that generated your QR.scala, i.e., ruby.

**Comment by matiasw** [comment]
Right: the Scala Hello, world at http://www.scala-lang.org/documentation/getting-started.html#the-hello-world-program gives the same error. So, we can safely conclude that my out-of-the-box Scala environment is at fault. I don't intend to take this any further.
Also, the QR.scala is identical to yours, so one step of the infinite chain can be considered successful..

**Comment by mame** [comment]
Okay, closing.  Thank you.
