### ISSUE TITLE
Error: Cannot find module 'prelude-ls'

### ISSUE THREAD

**Issue by CroMarmot** [mame/quine-relay#86]
```
##################################
##  93: LiveScript -> LLVM asm  ##
##################################

lsc QR.ls > QR.ll
module.js:442
    throw err;
    ^

Error: Cannot find module 'prelude-ls'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/nodejs/livescript/lib/ast.js:3:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by mame** [comment]
I guess your installation of LiveScript is broken.

**Comment by CroMarmot** [comment]
maybe the livescript on my linux distribution is something wrong.

install by `sudo npm install -g LiveScript` fixed
